Hw09 struct validator
tam-i13/hw-otus pull request #8
Opened 2023-02-26 20:52 UTC by tam-i13

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-02-27 07:23 UTC, gna69 requested changes

2023-02-27 07:23 UTC, gna69 commented on hw09_struct_validator/validator.go
> +				return vErr, err
Если одно из значений слайса будет некорректным
, то остальные не будут проверены, так как тут произойдет выход из функции проверки слайса. Предлагаю тут накапливать все ошибки для всех значений слайса и возвращать список ошибок для слайса.

2023-02-27 19:08 UTC, tam-i13 commented on hw09_struct_validator/validator.go
> +		errorString.WriteString(vv.Err.Error())
Спасибо, буду стараться сокращать.

2023-02-27 19:09 UTC, tam-i13 commented on hw09_struct_validator/validator.go
> +		case "len":
Поправил,

2023-02-27 19:12 UTC, tam-i13 commented on hw09_struct_validator/validator.go
> +				return vErr, err
Изначально  проверял все элементы в слайсе, но формирование ошибки (поле + ошибка) не давало покоя,  сейчас получилась реализация получше!

2023-02-28 14:32 UTC, gna69 approved these changes

2023-03-02 18:10 UTC, merged